### ISSUE TITLE
Cannot be installed with npm install + Example

### ISSUE THREAD

**Issue by ranhsd** [AmpMe/parse-server-test-runner#2]
Hi, It looks like that this module wasn't published to npm registry so I wanted to know if it is possible to publish it so users can install it via npm install parse-server-test-runner --save-dev. Currently in order to install it I point to the git repo in my package.json file 

Also, can you please provide an example on how to use it with Jasmine? 

Thanks.

**Comment by flovilmart** [comment]
@ranhsd I just published over npm. The example in the readme is for Jasmine :)

**Comment by ranhsd** [comment]
Hi @flovilmart thanks for the NPM. about the jasmine I already managed to write some unit tests. I have some issue with multiple spec.js files. If I create them then by default jasmine runs them in parallel and jasmine run the spec file before it initiate the parse server and then it fails... Do you have an idea how to fix it ? 

Thanks.
